"""empty message

Revision ID: 4a30f3968b2a
Revises: 
Create Date: 2026-04-08 13:03:57.571476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4a30f3968b2a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shippingentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entry_datetime', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('from_location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('to_location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('shipping_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cartons_count', sa.Integer(), nullable=False),
    sa.Column('shipping_company', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shippingentry')
    # ### end Alembic commands ###
